version: '3'
services:
  env:
    container_name: iiv-final-project
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
    restart: unless-stopped
    volumes:
      - ./wrkdir:/home/ubuntu/wrkdir
    ports:
      - 4422:22
      - 13389:3389
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
